CREATE TABLE IF NOT EXISTS public.seller_funnel_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id UUID NOT NULL REFERENCES public.sellers(id) ON DELETE CASCADE,
  seller_referral_id BIGINT NULL REFERENCES public.seller_referrals(id) ON DELETE SET NULL,
  referred_user_id UUID NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  affiliate_code TEXT NOT NULL,
  visitor_id TEXT NULL,
  event_type TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'link',
  path TEXT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT seller_funnel_events_event_type_check CHECK (
    event_type IN ('link_click', 'invite_visit', 'register_completed', 'pix_generated', 'pix_approved')
  ),
  CONSTRAINT seller_funnel_events_source_check CHECK (
    source IN ('link', 'manual', 'system')
  )
);

CREATE INDEX IF NOT EXISTS seller_funnel_events_seller_idx
  ON public.seller_funnel_events (seller_id, created_at DESC);

CREATE INDEX IF NOT EXISTS seller_funnel_events_type_idx
  ON public.seller_funnel_events (seller_id, event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS seller_funnel_events_referred_user_idx
  ON public.seller_funnel_events (referred_user_id, created_at DESC)
  WHERE referred_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS seller_funnel_events_unique_visitor_click_idx
  ON public.seller_funnel_events (seller_id, affiliate_code, event_type, visitor_id)
  WHERE event_type IN ('link_click', 'invite_visit') AND visitor_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS seller_funnel_events_unique_registration_idx
  ON public.seller_funnel_events (seller_id, event_type, referred_user_id)
  WHERE event_type = 'register_completed' AND referred_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS seller_funnel_events_unique_pix_idx
  ON public.seller_funnel_events (seller_id, event_type, ((metadata ->> 'pix_payment_id')))
  WHERE event_type IN ('pix_generated', 'pix_approved') AND (metadata ? 'pix_payment_id');

ALTER TABLE public.seller_funnel_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS seller_funnel_events_admin_select ON public.seller_funnel_events;
CREATE POLICY seller_funnel_events_admin_select
ON public.seller_funnel_events
FOR SELECT
TO authenticated
USING (public.is_admin_user(auth.uid()));

COMMENT ON TABLE public.seller_funnel_events IS
'Funil comercial dos vendedores: clique no link, visita, cadastro concluído, PIX gerado e PIX aprovado.';

CREATE OR REPLACE FUNCTION public.log_seller_funnel_event(
  p_seller_id UUID,
  p_affiliate_code TEXT,
  p_event_type TEXT,
  p_source TEXT DEFAULT 'link',
  p_visitor_id TEXT DEFAULT NULL,
  p_referred_user_id UUID DEFAULT NULL,
  p_seller_referral_id BIGINT DEFAULT NULL,
  p_path TEXT DEFAULT NULL,
  p_created_at TIMESTAMPTZ DEFAULT NOW(),
  p_metadata JSONB DEFAULT '{}'::JSONB
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event_type TEXT := LOWER(TRIM(COALESCE(p_event_type, '')));
  v_source TEXT := LOWER(TRIM(COALESCE(p_source, 'link')));
  v_affiliate_code TEXT := TRIM(COALESCE(p_affiliate_code, ''));
  v_visitor_id TEXT := NULLIF(LEFT(TRIM(COALESCE(p_visitor_id, '')), 120), '');
  v_path TEXT := NULLIF(LEFT(TRIM(COALESCE(p_path, '')), 255), '');
  v_metadata JSONB := COALESCE(p_metadata, '{}'::JSONB);
  v_event_id BIGINT;
  v_existing_id BIGINT;
  v_pix_payment_id TEXT := NULLIF(TRIM(COALESCE(v_metadata ->> 'pix_payment_id', '')), '');
BEGIN
  IF p_seller_id IS NULL THEN
    RETURN NULL;
  END IF;

  IF v_affiliate_code = '' THEN
    RETURN NULL;
  END IF;

  IF v_event_type NOT IN ('link_click', 'invite_visit', 'register_completed', 'pix_generated', 'pix_approved') THEN
    RAISE EXCEPTION 'Tipo de evento de funil inválido: %', p_event_type;
  END IF;

  IF v_source NOT IN ('link', 'manual', 'system') THEN
    v_source := 'link';
  END IF;

  IF p_seller_referral_id IS NULL AND p_referred_user_id IS NOT NULL THEN
    SELECT sr.id
    INTO p_seller_referral_id
    FROM public.seller_referrals sr
    WHERE sr.seller_id = p_seller_id
      AND sr.referred_user_id = p_referred_user_id
    ORDER BY sr.campaign_enabled_at DESC, sr.created_at DESC
    LIMIT 1;
  END IF;

  IF v_event_type IN ('link_click', 'invite_visit') AND v_visitor_id IS NOT NULL THEN
    SELECT sfe.id
    INTO v_existing_id
    FROM public.seller_funnel_events sfe
    WHERE sfe.seller_id = p_seller_id
      AND sfe.affiliate_code = v_affiliate_code
      AND sfe.event_type = v_event_type
      AND sfe.visitor_id = v_visitor_id
    LIMIT 1;

    IF v_existing_id IS NOT NULL THEN
      RETURN v_existing_id;
    END IF;
  END IF;

  IF v_event_type = 'register_completed' AND p_referred_user_id IS NOT NULL THEN
    SELECT sfe.id
    INTO v_existing_id
    FROM public.seller_funnel_events sfe
    WHERE sfe.seller_id = p_seller_id
      AND sfe.event_type = 'register_completed'
      AND sfe.referred_user_id = p_referred_user_id
    LIMIT 1;

    IF v_existing_id IS NOT NULL THEN
      RETURN v_existing_id;
    END IF;
  END IF;

  IF v_event_type IN ('pix_generated', 'pix_approved') AND v_pix_payment_id IS NOT NULL THEN
    SELECT sfe.id
    INTO v_existing_id
    FROM public.seller_funnel_events sfe
    WHERE sfe.seller_id = p_seller_id
      AND sfe.event_type = v_event_type
      AND sfe.metadata ->> 'pix_payment_id' = v_pix_payment_id
    LIMIT 1;

    IF v_existing_id IS NOT NULL THEN
      RETURN v_existing_id;
    END IF;
  END IF;

  INSERT INTO public.seller_funnel_events (
    seller_id,
    seller_referral_id,
    referred_user_id,
    affiliate_code,
    visitor_id,
    event_type,
    source,
    path,
    metadata,
    created_at
  )
  VALUES (
    p_seller_id,
    p_seller_referral_id,
    p_referred_user_id,
    v_affiliate_code,
    v_visitor_id,
    v_event_type,
    v_source,
    v_path,
    v_metadata,
    COALESCE(p_created_at, NOW())
  )
  RETURNING id INTO v_event_id;

  RETURN v_event_id;
END;
$$;

REVOKE ALL ON FUNCTION public.log_seller_funnel_event(UUID, TEXT, TEXT, TEXT, TEXT, UUID, BIGINT, TEXT, TIMESTAMPTZ, JSONB) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.log_seller_funnel_event(UUID, TEXT, TEXT, TEXT, TEXT, UUID, BIGINT, TEXT, TIMESTAMPTZ, JSONB) TO service_role, postgres;

CREATE OR REPLACE FUNCTION public.track_seller_funnel_event(
  p_affiliate_code TEXT,
  p_event_type TEXT,
  p_visitor_id TEXT DEFAULT NULL,
  p_path TEXT DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}'::JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_affiliate_code TEXT := TRIM(COALESCE(p_affiliate_code, ''));
  v_event_type TEXT := LOWER(TRIM(COALESCE(p_event_type, '')));
  v_seller_id UUID;
  v_event_id BIGINT;
BEGIN
  IF v_affiliate_code = '' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'missing_affiliate_code');
  END IF;

  IF v_event_type NOT IN ('link_click', 'invite_visit') THEN
    RAISE EXCEPTION 'Evento público não permitido: %', p_event_type;
  END IF;

  SELECT s.id
  INTO v_seller_id
  FROM public.sellers s
  WHERE s.seller_code = v_affiliate_code
  LIMIT 1;

  IF v_seller_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'seller_not_found');
  END IF;

  v_event_id := public.log_seller_funnel_event(
    v_seller_id,
    v_affiliate_code,
    v_event_type,
    'link',
    p_visitor_id,
    NULL,
    NULL,
    p_path,
    NOW(),
    COALESCE(p_metadata, '{}'::JSONB)
  );

  RETURN jsonb_build_object(
    'ok', true,
    'tracked', v_event_id IS NOT NULL,
    'event_id', v_event_id,
    'seller_id', v_seller_id
  );
END;
$$;

REVOKE ALL ON FUNCTION public.track_seller_funnel_event(TEXT, TEXT, TEXT, TEXT, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.track_seller_funnel_event(TEXT, TEXT, TEXT, TEXT, JSONB) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.handle_seller_referral_funnel_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.log_seller_funnel_event(
    NEW.seller_id,
    NEW.affiliate_code,
    'register_completed',
    COALESCE(NEW.source, 'link'),
    NULL,
    NEW.referred_user_id,
    NEW.id,
    '/register',
    COALESCE(NEW.created_at, NOW()),
    jsonb_build_object(
      'seller_referral_id', NEW.id,
      'source', COALESCE(NEW.source, 'link')
    )
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_seller_referrals_funnel_after_insert ON public.seller_referrals;
CREATE TRIGGER trg_seller_referrals_funnel_after_insert
AFTER INSERT ON public.seller_referrals
FOR EACH ROW
EXECUTE FUNCTION public.handle_seller_referral_funnel_event();

CREATE OR REPLACE FUNCTION public.handle_pix_payment_funnel_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_source TEXT;
  v_payload JSONB;
  v_old_approved BOOLEAN;
  v_new_approved BOOLEAN;
BEGIN
  v_source := CASE
    WHEN TG_OP = 'INSERT' THEN COALESCE(NEW.seller_source, 'system')
    ELSE COALESCE(NEW.seller_source, OLD.seller_source, 'system')
  END;

  IF TG_OP = 'INSERT' THEN
    IF NEW.seller_id IS NULL THEN
      RETURN NEW;
    END IF;

    v_payload := jsonb_build_object(
      'pix_payment_id', NEW.id,
      'mp_payment_id', NEW.mp_payment_id,
      'plan_id', NEW.plan_id,
      'amount', COALESCE(NEW.amount, 0),
      'status', NEW.status
    );

    PERFORM public.log_seller_funnel_event(
      NEW.seller_id,
      (SELECT s.seller_code FROM public.sellers s WHERE s.id = NEW.seller_id),
      'pix_generated',
      v_source,
      NULL,
      NEW.user_id,
      NEW.seller_referral_id,
      '/plans',
      COALESCE(NEW.created_at, NOW()),
      v_payload
    );

    IF COALESCE(LOWER(NEW.status), '') IN ('approved', 'paid', 'completed', 'authorized') OR NEW.plan_activated_at IS NOT NULL THEN
      PERFORM public.log_seller_funnel_event(
        NEW.seller_id,
        (SELECT s.seller_code FROM public.sellers s WHERE s.id = NEW.seller_id),
        'pix_approved',
        v_source,
        NULL,
        NEW.user_id,
        NEW.seller_referral_id,
        '/plans',
        COALESCE(NEW.plan_activated_at, NEW.updated_at, NEW.created_at, NOW()),
        v_payload || jsonb_build_object('approved_at', COALESCE(NEW.plan_activated_at, NEW.updated_at, NEW.created_at, NOW()))
      );
    END IF;

    RETURN NEW;
  END IF;

  v_old_approved := COALESCE(LOWER(OLD.status), '') IN ('approved', 'paid', 'completed', 'authorized') OR OLD.plan_activated_at IS NOT NULL;
  v_new_approved := COALESCE(LOWER(NEW.status), '') IN ('approved', 'paid', 'completed', 'authorized') OR NEW.plan_activated_at IS NOT NULL;

  IF NEW.seller_id IS NULL OR NOT v_new_approved OR v_old_approved THEN
    RETURN NEW;
  END IF;

  v_payload := jsonb_build_object(
    'pix_payment_id', NEW.id,
    'mp_payment_id', NEW.mp_payment_id,
    'plan_id', NEW.plan_id,
    'amount', COALESCE(NEW.amount, 0),
    'status', NEW.status,
    'approved_at', COALESCE(NEW.plan_activated_at, NEW.updated_at, NOW())
  );

  PERFORM public.log_seller_funnel_event(
    NEW.seller_id,
    (SELECT s.seller_code FROM public.sellers s WHERE s.id = NEW.seller_id),
    'pix_approved',
    v_source,
    NULL,
    NEW.user_id,
    NEW.seller_referral_id,
    '/plans',
    COALESCE(NEW.plan_activated_at, NEW.updated_at, NOW()),
    v_payload
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pix_payments_funnel_after_insert ON public.pix_payments;
CREATE TRIGGER trg_pix_payments_funnel_after_insert
AFTER INSERT ON public.pix_payments
FOR EACH ROW
EXECUTE FUNCTION public.handle_pix_payment_funnel_event();

DROP TRIGGER IF EXISTS trg_pix_payments_funnel_after_update ON public.pix_payments;
CREATE TRIGGER trg_pix_payments_funnel_after_update
AFTER UPDATE OF status, plan_activated_at, updated_at ON public.pix_payments
FOR EACH ROW
EXECUTE FUNCTION public.handle_pix_payment_funnel_event();

INSERT INTO public.seller_funnel_events (
  seller_id,
  seller_referral_id,
  referred_user_id,
  affiliate_code,
  event_type,
  source,
  path,
  metadata,
  created_at
)
SELECT
  sr.seller_id,
  sr.id,
  sr.referred_user_id,
  sr.affiliate_code,
  'register_completed',
  COALESCE(sr.source, 'link'),
  '/register',
  jsonb_build_object(
    'seller_referral_id', sr.id,
    'source', COALESCE(sr.source, 'link')
  ),
  COALESCE(sr.created_at, NOW())
FROM public.seller_referrals sr
WHERE NOT EXISTS (
  SELECT 1
  FROM public.seller_funnel_events sfe
  WHERE sfe.seller_id = sr.seller_id
    AND sfe.event_type = 'register_completed'
    AND sfe.referred_user_id = sr.referred_user_id
);

INSERT INTO public.seller_funnel_events (
  seller_id,
  seller_referral_id,
  referred_user_id,
  affiliate_code,
  event_type,
  source,
  path,
  metadata,
  created_at
)
SELECT
  px.seller_id,
  px.seller_referral_id,
  px.user_id,
  s.seller_code,
  'pix_generated',
  COALESCE(px.seller_source, 'system'),
  '/plans',
  jsonb_build_object(
    'pix_payment_id', px.id,
    'mp_payment_id', px.mp_payment_id,
    'plan_id', px.plan_id,
    'amount', COALESCE(px.amount, 0),
    'status', px.status
  ),
  COALESCE(px.created_at, NOW())
FROM public.pix_payments px
JOIN public.sellers s
  ON s.id = px.seller_id
WHERE px.seller_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.seller_funnel_events sfe
    WHERE sfe.seller_id = px.seller_id
      AND sfe.event_type = 'pix_generated'
      AND sfe.metadata ->> 'pix_payment_id' = px.id::TEXT
  );

INSERT INTO public.seller_funnel_events (
  seller_id,
  seller_referral_id,
  referred_user_id,
  affiliate_code,
  event_type,
  source,
  path,
  metadata,
  created_at
)
SELECT
  px.seller_id,
  px.seller_referral_id,
  px.user_id,
  s.seller_code,
  'pix_approved',
  COALESCE(px.seller_source, 'system'),
  '/plans',
  jsonb_build_object(
    'pix_payment_id', px.id,
    'mp_payment_id', px.mp_payment_id,
    'plan_id', px.plan_id,
    'amount', COALESCE(px.amount, 0),
    'status', px.status,
    'approved_at', COALESCE(px.plan_activated_at, px.updated_at, px.created_at, NOW())
  ),
  COALESCE(px.plan_activated_at, px.updated_at, px.created_at, NOW())
FROM public.pix_payments px
JOIN public.sellers s
  ON s.id = px.seller_id
WHERE px.seller_id IS NOT NULL
  AND (
    COALESCE(LOWER(px.status), '') IN ('approved', 'paid', 'completed', 'authorized')
    OR px.plan_activated_at IS NOT NULL
  )
  AND NOT EXISTS (
    SELECT 1
    FROM public.seller_funnel_events sfe
    WHERE sfe.seller_id = px.seller_id
      AND sfe.event_type = 'pix_approved'
      AND sfe.metadata ->> 'pix_payment_id' = px.id::TEXT
  );

CREATE OR REPLACE FUNCTION public.admin_get_seller_report(
  p_seller_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result JSONB;
BEGIN
  PERFORM public.assert_fatopago_admin();

  WITH seller_row AS (
    SELECT
      s.id,
      s.name,
      s.email,
      s.phone,
      s.cpf,
      s.notes,
      s.seller_code,
      s.is_active,
      s.avatar_url,
      s.created_at,
      'https://fatopago.com/convite/' || s.seller_code AS affiliate_link
    FROM public.sellers s
    WHERE s.id = p_seller_id
  ),
  referred_users AS (
    SELECT
      sr.id,
      sr.created_at,
      sr.affiliate_code,
      sr.referred_user_id,
      p.name,
      p.lastname,
      p.email,
      p.city,
      p.state,
      p.avatar_url
    FROM public.seller_referrals sr
    LEFT JOIN public.profiles p
      ON p.id = sr.referred_user_id
    WHERE sr.seller_id = p_seller_id
    ORDER BY sr.created_at DESC
  ),
  sales AS (
    SELECT
      pp.id,
      pp.user_id,
      COALESCE(p.name, 'Usuário') AS referred_name,
      COALESCE(p.lastname, '') AS referred_lastname,
      p.email AS referred_email,
      p.avatar_url AS referred_avatar_url,
      pp.plan_id,
      public.resolve_plan_purchase_amount(pp.plan_id, pp.validation_credit_total) AS amount,
      pp.status,
      pp.created_at
    FROM public.seller_referrals sr
    JOIN public.plan_purchases pp
      ON pp.user_id = sr.referred_user_id
    LEFT JOIN public.profiles p
      ON p.id = pp.user_id
    WHERE sr.seller_id = p_seller_id
      AND COALESCE(pp.status, '') <> 'cancelled'
    ORDER BY pp.created_at DESC
  ),
  funnel_summary AS (
    SELECT
      COUNT(*) FILTER (WHERE sfe.event_type = 'link_click')::INT AS link_clicks,
      COUNT(DISTINCT sfe.visitor_id) FILTER (WHERE sfe.event_type = 'link_click' AND sfe.visitor_id IS NOT NULL)::INT AS unique_link_clicks,
      COUNT(*) FILTER (WHERE sfe.event_type = 'invite_visit')::INT AS invite_visits,
      COUNT(DISTINCT sfe.visitor_id) FILTER (WHERE sfe.event_type = 'invite_visit' AND sfe.visitor_id IS NOT NULL)::INT AS unique_invite_visits,
      COUNT(*) FILTER (WHERE sfe.event_type = 'register_completed')::INT AS registrations,
      COUNT(DISTINCT sfe.referred_user_id) FILTER (WHERE sfe.event_type = 'register_completed' AND sfe.referred_user_id IS NOT NULL)::INT AS unique_registrations,
      COUNT(*) FILTER (WHERE sfe.event_type = 'pix_generated')::INT AS pix_generated,
      COUNT(DISTINCT sfe.referred_user_id) FILTER (WHERE sfe.event_type = 'pix_generated' AND sfe.referred_user_id IS NOT NULL)::INT AS unique_pix_generated,
      COUNT(*) FILTER (WHERE sfe.event_type = 'pix_approved')::INT AS pix_approved,
      COUNT(DISTINCT sfe.referred_user_id) FILTER (WHERE sfe.event_type = 'pix_approved' AND sfe.referred_user_id IS NOT NULL)::INT AS unique_pix_approved
    FROM public.seller_funnel_events sfe
    WHERE sfe.seller_id = p_seller_id
  ),
  funnel_events AS (
    SELECT
      sfe.id,
      sfe.event_type,
      sfe.source,
      sfe.created_at,
      sfe.visitor_id,
      sfe.referred_user_id,
      sfe.seller_referral_id,
      sfe.path,
      sfe.metadata,
      COALESCE(p.name, 'Visitante') AS referred_name,
      COALESCE(p.lastname, '') AS referred_lastname,
      p.email AS referred_email,
      p.city AS referred_city,
      p.state AS referred_state,
      p.avatar_url AS referred_avatar_url,
      NULLIF(sfe.metadata ->> 'plan_id', '') AS plan_id,
      NULLIF(sfe.metadata ->> 'mp_payment_id', '') AS mp_payment_id,
      COALESCE((sfe.metadata ->> 'amount')::NUMERIC, 0) AS amount
    FROM public.seller_funnel_events sfe
    LEFT JOIN public.profiles p
      ON p.id = sfe.referred_user_id
    WHERE sfe.seller_id = p_seller_id
    ORDER BY sfe.created_at DESC
    LIMIT 80
  )
  SELECT jsonb_build_object(
    'seller', COALESCE((SELECT to_jsonb(seller_row) FROM seller_row), '{}'::JSONB),
    'referred_users', COALESCE((SELECT jsonb_agg(to_jsonb(referred_users)) FROM referred_users), '[]'::JSONB),
    'sales', COALESCE((SELECT jsonb_agg(to_jsonb(sales)) FROM sales), '[]'::JSONB),
    'funnel_summary', COALESCE((SELECT to_jsonb(funnel_summary) FROM funnel_summary), '{}'::JSONB),
    'funnel_events', COALESCE((SELECT jsonb_agg(to_jsonb(funnel_events)) FROM funnel_events), '[]'::JSONB)
  )
  INTO v_result;

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_get_seller_report(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_get_seller_report(UUID) TO authenticated;
