CREATE TABLE IF NOT EXISTS public.plan_credit_restorations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_purchase_id UUID NOT NULL UNIQUE REFERENCES public.plan_purchases(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  restored_credit NUMERIC(12,2) NOT NULL CHECK (restored_credit >= 0),
  reason TEXT NOT NULL,
  compensation_applied_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_plan_credit_restorations_user_id
  ON public.plan_credit_restorations(user_id);

WITH restoration_candidates AS (
  SELECT
    pp.id AS plan_purchase_id,
    pp.user_id,
    GREATEST(COALESCE(pp.validation_credit_remaining, 0), 0)::NUMERIC(12,2) AS restored_credit
  FROM public.plan_purchases pp
  INNER JOIN public.profiles pr
    ON pr.id = pp.user_id
  WHERE pp.status = 'completed'
    AND GREATEST(COALESCE(pp.validation_credit_remaining, 0), 0) > 0.009
    AND NOT EXISTS (
      SELECT 1
      FROM public.pix_payments px
      WHERE px.activated_plan_purchase_id = pp.id
        AND px.status IN ('refunded', 'charged_back')
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.plan_credit_restorations pcr
      WHERE pcr.plan_purchase_id = pp.id
    )
)
INSERT INTO public.plan_credit_restorations (
  plan_purchase_id,
  user_id,
  restored_credit,
  reason
)
SELECT
  rc.plan_purchase_id,
  rc.user_id,
  rc.restored_credit,
  'Restauração automática de créditos após encerramento indevido por validade temporal'
FROM restoration_candidates rc;

WITH unapplied AS (
  SELECT
    pcr.user_id,
    SUM(pcr.restored_credit)::NUMERIC(12,2) AS total_credit
  FROM public.plan_credit_restorations pcr
  WHERE pcr.compensation_applied_at IS NULL
  GROUP BY pcr.user_id
)
UPDATE public.profiles p
SET
  compensatory_credit_balance = GREATEST(COALESCE(p.compensatory_credit_balance, 0), 0) + unapplied.total_credit,
  updated_at = NOW()
FROM unapplied
WHERE p.id = unapplied.user_id;

UPDATE public.plan_credit_restorations
SET compensation_applied_at = NOW()
WHERE compensation_applied_at IS NULL;

CREATE OR REPLACE FUNCTION public.submit_validation(
  p_task_id UUID,
  p_verdict BOOLEAN,
  p_justification TEXT DEFAULT NULL,
  p_proof_link TEXT DEFAULT NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID;
  v_profile RECORD;
  v_plan RECORD;
  v_task_closed BOOLEAN;
  v_task_status TEXT;
  v_is_admin_post BOOLEAN;
  v_category TEXT;
  v_cost NUMERIC(12,2);
  v_comp_balance NUMERIC(12,2) := 0;
  v_comp_used NUMERIC(12,2) := 0;
  v_plan_debit NUMERIC(12,2) := 0;
  v_validation_id UUID;
  v_current_cycle_start TIMESTAMPTZ;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN json_build_object('status', 'error', 'message', 'Não autenticado');
  END IF;

  SELECT
    content->>'category',
    COALESCE(consensus_reached, FALSE),
    COALESCE(consensus_status, 'open'),
    COALESCE(is_admin_post, FALSE)
  INTO
    v_category,
    v_task_closed,
    v_task_status,
    v_is_admin_post
  FROM public.news_tasks
  WHERE id = p_task_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN json_build_object('status', 'error', 'message', 'Tarefa não encontrada');
  END IF;

  IF NOT v_is_admin_post AND (v_task_closed OR v_task_status <> 'open') THEN
    RETURN json_build_object('status', 'error', 'message', 'Esta notícia não está mais aberta');
  END IF;

  SELECT * INTO v_plan
  FROM public.plan_purchases
  WHERE user_id = v_user_id
    AND status = 'active'
  ORDER BY started_at DESC
  LIMIT 1
  FOR UPDATE;

  SELECT c.cycle_start_at
  INTO v_current_cycle_start
  FROM public.get_weekly_cycle_window(NOW(), 0) c;

  IF EXISTS (
    SELECT 1
    FROM public.validations
    WHERE user_id = v_user_id
      AND task_id = p_task_id
      AND created_at >= v_current_cycle_start
  ) THEN
    RETURN json_build_object('status', 'error', 'message', 'Você já validou esta notícia neste ciclo');
  END IF;

  SELECT *
  INTO v_profile
  FROM public.profiles
  WHERE id = v_user_id
  FOR UPDATE;

  v_cost := GREATEST(COALESCE(public.get_validation_cost_by_category(v_category), 1.00), 0.01);
  v_comp_balance := GREATEST(COALESCE(v_profile.compensatory_credit_balance, 0), 0);
  v_comp_used := LEAST(v_comp_balance, v_cost);
  v_plan_debit := GREATEST(v_cost - v_comp_used, 0);

  IF v_plan_debit > 0 AND (v_plan.id IS NULL OR v_plan.validation_credit_remaining < v_plan_debit) THEN
    RETURN json_build_object('status', 'error', 'message', 'Crédito insuficiente');
  END IF;

  INSERT INTO public.validations (task_id, user_id, plan_purchase_id, verdict, justification, proof_link)
  VALUES (p_task_id, v_user_id, v_plan.id, p_verdict, p_justification, p_proof_link)
  RETURNING id INTO v_validation_id;

  UPDATE public.profiles
  SET compensatory_credit_balance = v_comp_balance - v_comp_used
  WHERE id = v_user_id;

  IF v_plan.id IS NOT NULL THEN
    UPDATE public.plan_purchases
    SET
      used_validations = used_validations + 1,
      validation_credit_remaining = validation_credit_remaining - v_plan_debit,
      status = CASE
        WHEN (validation_credit_remaining - v_plan_debit) <= 0.009 THEN 'completed'
        ELSE 'active'
      END
    WHERE id = v_plan.id;
  END IF;

  RETURN json_build_object('status', 'success', 'validation_id', v_validation_id);
END;
$$;

REVOKE ALL ON FUNCTION public.submit_validation(UUID, BOOLEAN, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.submit_validation(UUID, BOOLEAN, TEXT, TEXT) TO authenticated;
