CREATE TABLE IF NOT EXISTS public.cycle_winner_followup_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_number INTEGER NOT NULL REFERENCES public.cycle_winner_followups(cycle_number) ON DELETE CASCADE,
  winner_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  contacted BOOLEAN NOT NULL DEFAULT FALSE,
  prize_paid BOOLEAN NOT NULL DEFAULT FALSE,
  image_received BOOLEAN NOT NULL DEFAULT FALSE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.cycle_winner_followup_logs ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS cycle_winner_followup_logs_cycle_number_created_at_idx
  ON public.cycle_winner_followup_logs (cycle_number, created_at DESC);

INSERT INTO public.cycle_winner_followup_logs (
  cycle_number,
  winner_user_id,
  contacted,
  prize_paid,
  image_received,
  notes,
  created_at,
  created_by
)
SELECT
  f.cycle_number,
  f.winner_user_id,
  f.contacted,
  f.prize_paid,
  f.image_received,
  f.notes,
  COALESCE(f.updated_at, f.created_at, NOW()),
  f.updated_by
FROM public.cycle_winner_followups f
WHERE NOT EXISTS (
  SELECT 1
  FROM public.cycle_winner_followup_logs l
  WHERE l.cycle_number = f.cycle_number
);

CREATE OR REPLACE FUNCTION public.admin_update_cycle_winner_followup(
  p_cycle_number INTEGER,
  p_cycle_start_at TIMESTAMPTZ,
  p_cycle_end_at TIMESTAMPTZ,
  p_winner_user_id UUID DEFAULT NULL,
  p_contacted BOOLEAN DEFAULT FALSE,
  p_prize_paid BOOLEAN DEFAULT FALSE,
  p_image_received BOOLEAN DEFAULT FALSE,
  p_notes TEXT DEFAULT NULL
)
RETURNS public.cycle_winner_followups
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.cycle_winner_followups;
  v_clean_notes TEXT;
BEGIN
  PERFORM public.assert_fatopago_admin();

  IF COALESCE(p_cycle_number, 0) <= 0 THEN
    RAISE EXCEPTION 'Ciclo inválido';
  END IF;

  v_clean_notes := NULLIF(TRIM(COALESCE(p_notes, '')), '');

  INSERT INTO public.cycle_winner_followups (
    cycle_number,
    cycle_start_at,
    cycle_end_at,
    winner_user_id,
    contacted,
    prize_paid,
    image_received,
    notes,
    updated_by
  ) VALUES (
    p_cycle_number,
    COALESCE(p_cycle_start_at, NOW()),
    COALESCE(p_cycle_end_at, NOW()),
    p_winner_user_id,
    COALESCE(p_contacted, FALSE),
    COALESCE(p_prize_paid, FALSE),
    COALESCE(p_image_received, FALSE),
    v_clean_notes,
    auth.uid()
  )
  ON CONFLICT (cycle_number) DO UPDATE
  SET
    cycle_start_at = EXCLUDED.cycle_start_at,
    cycle_end_at = EXCLUDED.cycle_end_at,
    winner_user_id = EXCLUDED.winner_user_id,
    contacted = EXCLUDED.contacted,
    prize_paid = EXCLUDED.prize_paid,
    image_received = EXCLUDED.image_received,
    notes = EXCLUDED.notes,
    updated_by = auth.uid(),
    updated_at = NOW()
  RETURNING * INTO v_row;

  INSERT INTO public.cycle_winner_followup_logs (
    cycle_number,
    winner_user_id,
    contacted,
    prize_paid,
    image_received,
    notes,
    created_by
  ) VALUES (
    v_row.cycle_number,
    v_row.winner_user_id,
    v_row.contacted,
    v_row.prize_paid,
    v_row.image_received,
    v_row.notes,
    auth.uid()
  );

  RETURN v_row;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_update_cycle_winner_followup(INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, UUID, BOOLEAN, BOOLEAN, BOOLEAN, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_update_cycle_winner_followup(INTEGER, TIMESTAMPTZ, TIMESTAMPTZ, UUID, BOOLEAN, BOOLEAN, BOOLEAN, TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_list_cycle_winner_followup_logs(
  p_cycle_limit INTEGER DEFAULT 16,
  p_log_limit INTEGER DEFAULT 8
)
RETURNS TABLE (
  id BIGINT,
  cycle_number INTEGER,
  winner_user_id UUID,
  contacted BOOLEAN,
  prize_paid BOOLEAN,
  image_received BOOLEAN,
  notes TEXT,
  created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.assert_fatopago_admin();

  RETURN QUERY
  WITH recent_cycles AS (
    SELECT DISTINCT f.cycle_number
    FROM public.cycle_winner_followups f
    ORDER BY f.cycle_number DESC
    LIMIT GREATEST(COALESCE(p_cycle_limit, 16), 1)
  ),
  ranked_logs AS (
    SELECT
      l.*,
      ROW_NUMBER() OVER (PARTITION BY l.cycle_number ORDER BY l.created_at DESC, l.id DESC) AS rn
    FROM public.cycle_winner_followup_logs l
    INNER JOIN recent_cycles c
      ON c.cycle_number = l.cycle_number
  )
  SELECT
    rl.id,
    rl.cycle_number,
    rl.winner_user_id,
    rl.contacted,
    rl.prize_paid,
    rl.image_received,
    rl.notes,
    rl.created_at
  FROM ranked_logs rl
  WHERE rl.rn <= GREATEST(COALESCE(p_log_limit, 8), 1)
  ORDER BY rl.cycle_number DESC, rl.created_at DESC, rl.id DESC;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_list_cycle_winner_followup_logs(INTEGER, INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_list_cycle_winner_followup_logs(INTEGER, INTEGER) TO authenticated;
