CREATE TABLE IF NOT EXISTS public.security_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE,
  source TEXT NOT NULL,
  category TEXT NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('critical', 'high', 'medium', 'low')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  occurrence_count INTEGER NOT NULL DEFAULT 1 CHECK (occurrence_count >= 1),
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  acknowledged_at TIMESTAMPTZ NULL,
  acknowledged_by UUID NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  resolved_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_security_alerts_open_sort
  ON public.security_alerts (acknowledged_at, severity, last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_security_alerts_source_category
  ON public.security_alerts (source, category);

ALTER TABLE public.security_alerts ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.security_alerts FROM PUBLIC;
REVOKE ALL ON TABLE public.security_alerts FROM anon;
REVOKE ALL ON TABLE public.security_alerts FROM authenticated;

CREATE OR REPLACE FUNCTION public.raise_security_alert(
  p_event_key TEXT,
  p_source TEXT,
  p_category TEXT,
  p_severity TEXT,
  p_title TEXT,
  p_message TEXT,
  p_metadata JSONB DEFAULT '{}'::JSONB
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event_key TEXT := BTRIM(COALESCE(p_event_key, ''));
  v_source TEXT := BTRIM(COALESCE(p_source, ''));
  v_category TEXT := BTRIM(COALESCE(p_category, ''));
  v_severity TEXT := LOWER(BTRIM(COALESCE(p_severity, 'medium')));
  v_title TEXT := BTRIM(COALESCE(p_title, 'Alerta de segurança'));
  v_message TEXT := BTRIM(COALESCE(p_message, 'Evento crítico detectado.'));
  v_metadata JSONB := COALESCE(p_metadata, '{}'::JSONB);
  v_id BIGINT;
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role'
     AND NOT public.is_admin_user(auth.uid()) THEN
    RAISE EXCEPTION 'Acesso negado para registrar alertas de segurança.';
  END IF;

  IF v_event_key = '' OR v_source = '' OR v_category = '' THEN
    RAISE EXCEPTION 'Parâmetros obrigatórios ausentes para alerta de segurança.';
  END IF;

  IF v_severity NOT IN ('critical', 'high', 'medium', 'low') THEN
    RAISE EXCEPTION 'Severidade inválida para alerta de segurança.';
  END IF;

  INSERT INTO public.security_alerts (
    event_key,
    source,
    category,
    severity,
    title,
    message,
    metadata,
    occurrence_count,
    first_seen_at,
    last_seen_at,
    acknowledged_at,
    acknowledged_by,
    resolved_at,
    created_at,
    updated_at
  )
  VALUES (
    v_event_key,
    v_source,
    v_category,
    v_severity,
    v_title,
    v_message,
    jsonb_strip_nulls(v_metadata),
    1,
    NOW(),
    NOW(),
    NULL,
    NULL,
    NULL,
    NOW(),
    NOW()
  )
  ON CONFLICT (event_key) DO UPDATE
  SET
    source = EXCLUDED.source,
    category = EXCLUDED.category,
    severity = EXCLUDED.severity,
    title = EXCLUDED.title,
    message = EXCLUDED.message,
    metadata = EXCLUDED.metadata,
    occurrence_count = public.security_alerts.occurrence_count + 1,
    last_seen_at = NOW(),
    acknowledged_at = NULL,
    acknowledged_by = NULL,
    resolved_at = NULL,
    updated_at = NOW()
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.raise_security_alert(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.raise_security_alert(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, JSONB) TO service_role;

CREATE OR REPLACE FUNCTION public.admin_list_security_alerts(
  p_limit INTEGER DEFAULT 50,
  p_include_acknowledged BOOLEAN DEFAULT TRUE
)
RETURNS TABLE (
  id BIGINT,
  event_key TEXT,
  source TEXT,
  category TEXT,
  severity TEXT,
  title TEXT,
  message TEXT,
  metadata JSONB,
  occurrence_count INTEGER,
  first_seen_at TIMESTAMPTZ,
  last_seen_at TIMESTAMPTZ,
  acknowledged_at TIMESTAMPTZ,
  acknowledged_by UUID,
  resolved_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_limit INTEGER := LEAST(GREATEST(COALESCE(p_limit, 50), 1), 200);
BEGIN
  PERFORM public.assert_fatopago_admin();

  RETURN QUERY
  SELECT
    sa.id,
    sa.event_key,
    sa.source,
    sa.category,
    sa.severity,
    sa.title,
    sa.message,
    sa.metadata,
    sa.occurrence_count,
    sa.first_seen_at,
    sa.last_seen_at,
    sa.acknowledged_at,
    sa.acknowledged_by,
    sa.resolved_at
  FROM public.security_alerts sa
  WHERE p_include_acknowledged OR sa.acknowledged_at IS NULL
  ORDER BY
    CASE WHEN sa.acknowledged_at IS NULL THEN 0 ELSE 1 END,
    CASE sa.severity
      WHEN 'critical' THEN 0
      WHEN 'high' THEN 1
      WHEN 'medium' THEN 2
      ELSE 3
    END,
    sa.last_seen_at DESC
  LIMIT v_limit;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_list_security_alerts(INTEGER, BOOLEAN) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_list_security_alerts(INTEGER, BOOLEAN) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_acknowledge_security_alert(
  p_alert_id BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.assert_fatopago_admin();

  UPDATE public.security_alerts
  SET
    acknowledged_at = NOW(),
    acknowledged_by = auth.uid(),
    updated_at = NOW()
  WHERE id = p_alert_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Alerta de segurança não encontrado.';
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_acknowledge_security_alert(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_acknowledge_security_alert(BIGINT) TO authenticated;
